### ISSUE TITLE
Usage in a browser 

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/jaeger-client-node#109]
Hello,

I have a question, can this library be used in a web browser?

-- update Jan 24 2020 --
https://github.com/jaegertracing/jaeger-client-javascript/issues/1

**Comment by yurishkuro** [comment]
not in the current from. The plan was to pull the core logic from this library into jaeger-client-javascript and leave Node.js specific logic here.

In particular, one main change would be to replace UDP sender with an HTTP sender that can submit the spans directly to the backend, since UDP won't work from the browser.

This is on our roadmap for later in the year, not a high priority right now, but as always contributions are welcome.

**Comment by pavolloffay** [comment]
Thanks it looks promising :+1:. I could take a look at it soon.

Is it possible to send spans via TCP to backend at the moment? directly to collector? Could you please point me at code? (I'm still not very familiar with the backend components).

**Comment by yurishkuro** [comment]
The collectors currently expose TChannel-thrift ports only. 

https://github.com/uber/jaeger/blob/master/cmd/collector/main.go#L70

**Comment by pavolloffay** [comment]
@karelhala did some work on this https://github.com/uber/jaeger-client-node/compare/master...karelhala:browser-client

I will proceed but I guess we need REST endpoint on the collector side.

**Comment by yurishkuro** [comment]
What I would like to happen is to not duplicate the core tracer implementation, but to extract the shared part and have two shims, one for Node another for the browsers. I believe that's what lightstep did with theirs. We have a repo for that "core" part, and probably the browser shim, while the Node shim can remain in the current Node client repo.

https://github.com/uber/jaeger-client-javascript

**Comment by pavolloffay** [comment]
Agree, as much as possible should be reused.

About https://github.com/uber/jaeger-client-javascript, there is this https://lernajs.io/ project  for managing multiple packages in one repository. We could have `core`, `tchannel-reporter`, `rest-reporter`...

**Comment by tiffon** [comment]
I highly recommend [lerna](https://github.com/lerna/lerna), it's very handy and intended for exactly this type of situation.

Some examples of it in action:
 
- [babel/packages](https://github.com/babel/babel/tree/master/packages) - Packages for [babel](http://babeljs.io/)
- [jest/packages](https://github.com/facebook/jest/tree/master/packages) - Packages for [Jest](https://facebook.github.io/jest/) test framework

**Comment by pavolloffay** [comment]
I remember that we have talked about HTTP json endpoint on the server side which requires to define jaeger JSON model. Could we use just thrift with something like this https://www.npmjs.com/package/browser-thrift?

**Comment by yurishkuro** [comment]
I suppose, but it would pull additional dependencies into the browser.

**Comment by tiffon** [comment]
I did a quick check on the exported file size of browser-thrift.

Minified, it's about `151kb`, `42kb` after gzip.

But, most of the size comes from [bluebird](https://github.com/petkaantonov/bluebird), which seems to be [exported](https://github.com/vh/browser-thrift/blob/master/src/index.js#L32), but not used (not sure why).

Removing bluebird reduces the size to `69kb`, `20kb` after gzip. 

Looks like we might be able to remove bluebird (if it's not actually being used) or replace it with the native [`Promise`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#Browser_compatibility), which is pretty [well supporterd](https://caniuse.com/#feat=promises).

**Comment by MarckK** [comment]
Re [lerna](https://github.com/lerna/lerna): interesting writeup on [PouchDB's](https://pouchdb.com/) experience using lerna with a monorepo can be found [here](https://gist.github.com/nolanlawson/457cdb309c9ec5b39f0d420266a9faa4), with [Henry Zhu](https://github.com/hzoo) of [Babel](https://github.com/babel/babel) weighing in.

**Comment by yurishkuro** [comment]
20kb still sounds like a lot for functionality that is not absolutely necessary. I still think the browser client should report spans in plain JSON

**Comment by felixfbecker** [comment]
So is the plan to bake in JSON support into the Jaeger backend or to provide a backend proxy that converts the JSON?

**Comment by yurishkuro** [comment]
The plan is to support JSON on the backend. We already can accept Zipkin v2 JSON, but we haven't decided what Jaeger JSON should look like. Possible options are the Jaeger UI's JSON format, or the serialized format of the domain model (merging those too wouldn't be the worst thing either).

**Comment by MarckK** [comment]
Well, this might be left-field (and very green), but:
[gRPC-Web](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-WEB.md) seems very interesting
It's still being developed and is subject to change. 
However, Improbable have [built and are using in production](https://improbable.io/games/blog/grpc-web-moving-past-restjson-towards-type-safe-web-apis) something similar. 
They have open sourced [their gRPC-web](https://github.com/improbable-eng/grpc-web).

**Comment by felixfbecker** [comment]
We are looking to migrate from LightStep to Jaeger at Souregraph and I just stumpled across this issue again. Is there any active work or plans on the roadmap for this? 😔

**Comment by yurishkuro** [comment]
There was some work started in https://github.com/jaegertracing/jaeger-client-javascript/issues/1, but stalled. Using OpenTelemetry-js might be a better option at this point.

**Comment by silvairsoares** [comment]
While we have no news on this subject, I continue using the architecture below. Unfortunately, with the burden of duplicating http calls (Angular Frontend => BFF .Net => API Gateway instead of Angular Frontend => API Gateway) directly from Angular Frontend), in order to maintain end-to-end traceability.

![Angular Opentracing](https://user-images.githubusercontent.com/18450095/106274311-d6f13f00-6212-11eb-8f9d-10c2d396e89d.jpg)
