### ISSUE TITLE
(Feature request) Typescript definitions

### ISSUE THREAD

**Issue by julianste** [jaegertracing/jaeger-client-node#118]
It would be nice to have typescript definition files (see [Writing Definition Files](https://typescript.codeplex.com/wikipage?title=Writing%20Definition%20%28.d.ts%29%20Files))

**Comment by yurishkuro** [comment]
we have Flow definitions. Given that this lib is an implementation of OpenTracing API (which does have TS definition), what would be the use case for us creating our own?

**Comment by julianste** [comment]
Hi @yurishkuro, thanks for your response.
I would need TS Def. Files in order to do an normal `import` instead of a `require` in order to have typed variables.
I understand, that when using OpenTracing and the jaeger-tracer, I can do it like this:
```javascript
import * as opentracing from "opentracing";
var initTracer = require('jaeger-client').initTracer;
var tracer = initTracer(jaegerConfig, options);
```
But initTracer and tracer is now of `any`-type.
What do you mean by flow definitions?

**Comment by yurishkuro** [comment]
Flow is the semi-type system we use to validate ES6 code: https://github.com/uber/jaeger-client-node/tree/master/src/_flow.

> But initTracer and tracer is now of any-type.

Isn't it possible to force-cast it to the `opentracing.Tracer` type?

**Comment by julianste** [comment]
Yes that's possible although the `opentracing.Tracer` interface doesnt specify e.g. a `close` method. 
But I'm fine with this solution, thanks!

**Comment by jadengore** [comment]
@yurishkuro I think TypeScript definitions are a valid feature request for this project. TypeScript is as popular as Flow, and it shouldn't be too hard to provide both.

**Comment by yurishkuro** [comment]
as I have commented above, I don't think we have any **conceptual** objections, but there are many practical reasons against doing that:
  * we don't have capacity to undertake this rewrite
  * the rewrite may be quite large
  * due to size, it may be quite risky
  * the value proposition is unclear, given that the users of the library are not supposed to be exposed to much of its API, instead using the OpenTracing API, which is already in typescript

**Comment by smbell** [comment]
That's what I expected. I don't have the bandwidth to take it on myself right now, but if I do end up with the time I might give it a go in a fork and see what it looks like.

The value proposition to me is mainly in the span context. In the opentracing span_context.js there is the comment

>// The SpanContext is entirely implementation dependent

and, until literally about an hour ago, the open tracing span context was completely empty. Now it's interface is incompatible with the span context in this library.

**Comment by Bessonov** [comment]
More and more projects switch from flow or js to TypeScript. Native ts is better than any workarounds like internal/external definitions or flow.

Another thing is, that IDEs like vscode pick up ts definitions for auto completion even if using project is js based.

> the success criteria would include having unit tests that verify that those typescript definitions are in sync with he actual types

AFAIK it's impossible, if you add internal or external definitions, but:

> due to size, it may be quite risky

In my opinion usage of ts it's less risky than usage of flow. But you get more nice benefits.

BTW, external definitions are available: https://www.npmjs.com/package/@types/jaeger-client
