### ISSUE TITLE
Reference Errror

### ISSUE THREAD

**Issue by edukondalugorla** [jaegertracing/jaeger-client-node#147]
Hi I am new to jaeger,  When i run below given initialization code, I am getting "Reference Error metrics is not defined " . How to define metrics, logger variables. 

My initialization sample code  below.
----------------------
var initTracer = require('jaeger-client').initTracer;
var config = {
  'serviceName': 'my-awesome-service'
};
var options = {
  'tags': {
    'my-awesome-service.version': '1.1.2'
  },
  'metrics': metrics,
  'logger': logger
};
var tracer = initTracer(config, options);

**Comment by black-adder** [comment]
metrics and logger are optional variables if you're just trying jaeger out. If you do want to use them, you would have to pass in a logger that has the implements: https://github.com/uber/jaeger-client-node/blob/master/src/_flow/logger.js and a [metrics](https://github.com/uber/jaeger-client-node/blob/master/src/metrics/metrics.js) object where your metricsfactory looks like: https://github.com/uber/jaeger-client-node/blob/master/src/_flow/metrics.js#L42

Now that I've typed this all out, it doesn't seem very intuitive. I'll add some documentation for it.
