### ISSUE TITLE
Support tags injection via JAEGER_TAGS environment variable

### ISSUE THREAD

**Issue by rabbitstack** [jaegertracing/jaeger-client-node#152]
For the sake of consistency, it would be useful if tags could be aggregated via `JAEGER_TAGS` environment variable like in the Java client.

**Comment by ledor473** [comment]
@black-adder I think this can be closed now since this is merged https://github.com/jaegertracing/jaeger-client-node/pull/296

**Comment by yurishkuro** [comment]
+1, closing
