### ISSUE TITLE
Tracer.extract does not return null when no trace context is found in HTTP headers

### ISSUE THREAD

**Issue by thamion** [jaegertracing/jaeger-client-node#162]
According to the [specs](https://github.com/jaegertracing/jaeger-client-node/blob/816827fd5efd2a1d60d978d94ccacb6940ce62ca/src/tracer.js#L291) `Tracer.extract` should return `null` when no trace context is found. 

However, for HTTP requests with no span context, not `null` but a `SpanContext` with many undefined properties is returned. I believe the problem is in [text_map_codec](https://github.com/jaegertracing/jaeger-client-node/blob/816827fd5efd2a1d60d978d94ccacb6940ce62ca/src/propagators/text_map_codec.js#L61) which doesn't check if a trace or span id exists.

**Comment by yurishkuro** [comment]
sounds like a bug. However, we have a use case to return SpanContext with empty traceID but other fields set which is used for starting debug traces.

**Comment by yurishkuro** [comment]
Opened https://github.com/opentracing/specification/issues/104

**Comment by ThomWright** [comment]
We've had a problem which I think is related (had to debug though).

Our code looks like this:

```typescript
const parentContext = tracer.extract(
  FORMAT_HTTP_HEADERS,
  headers,
)
const spanOptions: opentracing.SpanOptions = {
  startTime: startTime.getTime(),
  tags: {
    // ...
  },
}

// Adding this causes problems
if (parentContext != null) {
  spanOptions.references = [opentracing.followsFrom(parentContext)]
}
```

We get the following error:

`Failed to append spans in reporter: error converting span to Thrift: spanId: missing required field "spanId" with id 4 on SpanRef`

We've needed to change it to the following:

```typescript
if (parentContext != null) {
  if ((parentContext as any)._spanIdStr != null) {
    spanOptions.references = [opentracing.followsFrom(parentContext)]
  }
}
```

Curiously we don't get the same error with `spanOptions.childOf`. Should I raise a separate issue for this?

**Comment by yurishkuro** [comment]
`.references` are not supposed to be mutated after creating the span.

**Comment by ThomWright** [comment]
> `.references` are not supposed to be mutated after creating the span.

It isn't mutated after creating the span. See my edited comment above. The `spanOptions` are mutated before creating the span.

**Comment by yurishkuro** [comment]
@ThomWright it's odd, looks like a bug.
