### ISSUE TITLE
Support Zipkin HTTP B3 propagation format

### ISSUE THREAD

**Issue by dcarney** [jaegertracing/jaeger-client-node#165]
Support for Zipkin-style `X-B3-*` headers has already been added to the [go client](https://github.com/jaegertracing/jaeger-client-go/tree/master/zipkin) and the [java client](https://github.com/jaegertracing/jaeger-client-java/tree/master/jaeger-zipkin).  It appears to be straightforward to add such support to the node client as well.

Per the [contribution guidelines](https://github.com/jaegertracing/jaeger-client-node/blob/master/CONTRIBUTING.md), I'm opening an issue before submitting a PR to add this functionality.

The bulk of the new "propagator" implementation for Zipkin-style headers would be similar to the current `TextMapCodec`.  I've got a working prototype (I called it a `ZipkinB3TextMapCodec`, after the [go implementation of the same name](https://github.com/jaegertracing/jaeger-client-go/tree/master/zipkin)) that I could clean up and submit in a PR.

**Comment by yurishkuro** [comment]
+1

**Comment by afoninsky** [comment]
> I've got a working prototype
@dcarney  could you please point to this prototype?

**Comment by dcarney** [comment]
@afoninsky Thanks for the reminder!  I'm cleaning up my PR right now, and will submit it today.

**Comment by dcarney** [comment]
Submitted PR #175

**Comment by yurishkuro** [comment]
Thanks!

**Comment by yurishkuro** [comment]
Released as 3.7.0
