### ISSUE TITLE
Support for HTTP sender

### ISSUE THREAD

**Issue by rabbitstack** [jaegertracing/jaeger-client-node#170]
Because Java and Go clients already support HTTP senders to emit span requests directly to the collector, it would be a nice addition if Node.js client could be capable to transport spans over HTTP too.

**Comment by yurishkuro** [comment]
Depends on most of https://github.com/jaegertracing/jaeger/issues/723

**Comment by jonahgeorge** [comment]
@yurishkuro Are you opposed to adding support to this library for sending Thrift over HTTP prior to the changes proposed in #723?

**Comment by yurishkuro** [comment]
not at all

**Comment by keitwb** [comment]
@jonahgeorge did you already start work on this?  If not, we are going to take a crack at it because we need it as well.

**Comment by jonahgeorge** [comment]
I haven't gotten around to it, please do!
