### ISSUE TITLE
Update .travis.yml (and improve Travis runtimes)

### ISSUE THREAD

**Issue by MarckK** [jaegertracing/jaeger-client-node#190]
[Update node versions specified in .travis.yml](https://github.com/jaegertracing/jaeger-client-node/pull/191)

Our Travis CI takes a while to run, we could make it faster by removing some of the specified node versions.

Comments and other suggestions to improve Travis runtimes welcome.

**Comment by yurishkuro** [comment]
I think we can drop 5, but the other versions are needed for backwards compatibility guarantees.
