### ISSUE TITLE
Spans being dropped by udp_sender

### ISSUE THREAD

**Issue by black-adder** [jaegertracing/jaeger-client-node#206]
I wrote a load test that creates 100 traces at once. The udp_sender seemingly successfully sends the batches to agent with no errors. However,  I check the UI and I don't see all 100 traces. So I used tcpdump to see how many packets were arriving at the agent and indeed some packets were missing.

Given the fire and forget nature of udp, I guess this is valid? However, the dropped spans aren't observable since the dgram udp socket never returns an error even if the packet is dropped.

**Comment by black-adder** [comment]
@tiffon you know anything we could do about this?

**Comment by tiffon** [comment]
@black-adder How is this handled in the other clients? As long as the approach is feasible and practical in node, we should aim for the same approach, or similar to be consistent.

**Comment by black-adder** [comment]
sigghhhhh, it was https://github.com/jaegertracing/jaeger-client-node/issues/124
