### ISSUE TITLE
Full example of configuring client for All-In-One jaeger docker

### ISSUE THREAD

**Issue by abraithwaite** [jaegertracing/jaeger-client-node#213]
I spent a while going over the docs and reading the code trying to figure out how to configure opentracing + jaeger node client to send spans to the local jaeger instance.

It would be nice to have a complete and tested example of configuring the tracer implementation to send to the all-in-one jaeger docker.

The closest I've gotten to a working solution, I ran into #210.  After manually patching the library to return a static length for the buffer calculation, I saw the library attempting to send but to no success.

I've successfully sent spans with the go libraries without issues.

**Comment by yurishkuro** [comment]
@abraithwaite can you post your solution here?

**Comment by wiredmartian** [comment]
Did this ever take flight? I'm looking for a comprehensive example on how to tie your client with jaeger docker.

**Comment by yurishkuro** [comment]
There is no special configuration required to send to a jaeger-agent running on the local host, which is what all-in-one provides.
