### ISSUE TITLE
Pre-commit hook fails

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-node#225]
I am running under `nvm use 6` and `git commit` always fails with
```
husky > npm run -s precommit (node v0.10.32)


/Users/yurishkuro/Uber/jaeger-client-node/node_modules/lint-staged/index.js:5
const cmdline = require('commander')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

husky > pre-commit hook failed (add --no-verify to bypass)
```

which I think is caused by the fact that the hook is trying to run with Node 0.10, which would be incompatible with my installed node_modules.

cc @MarckK

**Comment by MarckK** [comment]
I can't get this error to reproduce. It _might_ be because your nvm default is set to node v0.10.32; whereas mine is set to v7.10.0 and thus, for me, the pre-commit hook always runs as `husky > npm run -s precommit (node v7.10.0)`, no matter which node version I'm using.

```
jaeger-client-node git:(callbacksUDPSender) nvm use 0.10.32
Now using node v0.10.32 (npm v1.4.28)
jaeger-client-node git:(callbacksUDPSender) ✗ git commit -m "Small edits of syntax"
husky > npm run -s precommit (node v7.10.0)

 ✔ Running tasks for *.{js,json,md}
[callbacksUDPSender 6d02989] Small edits of syntax
 3 files changed, 3 insertions(+), 13 deletions(-)

```

```
jaeger-client-node git:(callbacksUDPSender) nvm use 6
Now using node v6.11.2 (npm v3.10.10)
jaeger-client-node git:(callbacksUDPSender) ✗ git commit -m "Small edits of syntax"
husky > npm run -s precommit (node v7.10.0)

 ✔ Running tasks for *.{js,json,md}
[callbacksUDPSender 9390097] Small edits of syntax
 3 files changed, 3 insertions(+), 13 deletions(-)
```

**Comment by MarckK** [comment]
If the problem and solution is as simple as this, it might require a note somewhere? 
On the other hand, there's a new module for ['dependency-less (almost) per user customisable git hooks'](https://github.com/sandfox/chowchow), which is green and requires tests and I haven't used yet, but looks really interesting.

**Comment by yurishkuro** [comment]
I think my point is that the hook should be using the Node version active at the moment in the repo, not some random system/user default. I was looking where in the previous commits the actual hook was changed, but couldn't find it.

**Comment by MarckK** [comment]
I believe husky is written to select the node version used for the pre-commit hook; this isn't something I configured, so it wouldn't be in any of my commits. 

It is likely possible that we could write an override so that the hook uses the Node version active at the moment in the repo -- although, then it will likely break on node v0.10.

**Comment by yurishkuro** [comment]
Could you explain how exactly you added the hook? I saw the husky in the commit, but no references to git files.

**Comment by MarckK** [comment]
Your local .git/hooks/files will be populated by husky; my understanding is that husky does this during installation (husky is a [dependency](https://github.com/jaegertracing/jaeger-client-node/blob/0f6a273bc219b38f9f8189ea752d18962710cca8/package.json#L57)).  The [precommit](https://github.com/jaegertracing/jaeger-client-node/blob/0f6a273bc219b38f9f8189ea752d18962710cca8/package.json#L67) script is handled by husky and we've configured it to run `lint-staged`. [Lint-staged](https://github.com/jaegertracing/jaeger-client-node/blob/0f6a273bc219b38f9f8189ea752d18962710cca8/package.json#L42) looks at the configuration we've written in the [lint-staged](https://github.com/jaegertracing/jaeger-client-node/blob/0f6a273bc219b38f9f8189ea752d18962710cca8/package.json#.L76) section of our package.json.

**Comment by yurishkuro** [comment]
Yes, it's a good topic for a blog post. Another one is the matrix "build w/ 6 - test w/ X" you setup, I think it's super useful.

I looked at husky docs, it says "If nvm is installed, husky will try to use the default/current installed Node version or use the project .nvmrc." So that's probably the solution, since we don't have .nvmrc in this project like we do in jaeger-ui:
```
$ cat ../jaeger-ui/.nvmrc
6
```
