### ISSUE TITLE
Add @tiffon as maintainer of jaeger-client-node

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-node#229]
Joe (@tiffon) is our resident JS expert and maintainer of Jaeger UI, but he cannot even approve PRs in this repo (e.g. [here](https://github.com/jaegertracing/jaeger-client-node/pull/226#issuecomment-367420426)). I propose to add him as maintainer.

@pavolloffay @vprithvi @black-adder please vote

**Comment by black-adder** [comment]
+1

**Comment by pavolloffay** [comment]
+1

**Comment by black-adder** [comment]
That's a majority?

**Comment by vprithvi** [comment]
+1

**Comment by yurishkuro** [comment]
Adding
