### ISSUE TITLE
Stop testing with Node 0.12

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-node#236]
Note sure why it was added in the first place since @ Uber we only used 0.10. The tests for 0.12 are spontaneously failing during `npm install`.

If anyone depends on 0.12 compatibility, please comment here.

@dcarney @objectiser @pavolloffay @lipis @OmgImAlexis @frankgreco @eldadcohen1

**Comment by dcarney** [comment]
@yurishkuro No need here, I'm long past 0.12. :+1:
