### ISSUE TITLE
Large spans not sending correctly

### ISSUE THREAD

**Issue by yrsh** [jaegertracing/jaeger-client-node#242]
Hello!
We have problems with large spans, when we call span.log with data greater than UDP_PACKET_MAX_LENGTH, these spans do not reach correctly and are not visible later in the UI.
Does jaeger can not send (or split them to several packets) large spans?

**Comment by yurishkuro** [comment]
I think the best solution would be to support HTTP sender (#170) which would have much higher limits on the span size.

Other things that could be done are:
  * flushing partial spans (https://github.com/jaegertracing/jaeger/issues/729)
  * limiting the number and size of logs allowed per span (Lightstep does that)

**Comment by claudio-viola** [comment]
Related you can use flushIntervalMs to flush more frequently that would reduce the size .
the HTTP Sender is already in master and i tested it works.
So this can be closed.
Related: https://github.com/jaegertracing/jaeger-client-node/issues/293

**Comment by yurishkuro** [comment]
Thanks @claudio-viola
