### ISSUE TITLE
jaeger javascript client: how to use followsFrom ?

### ISSUE THREAD

**Issue by chenyg0911** [jaegertracing/jaeger-client-node#247]
childOf as sample is OK.
but when I try to use followsFrom as opentracing javascrip doc example, like below:

```

const { Tags, FORMAT_TEXT_MAP,opentracing } = require('opentracing');
....
    const parentSpanContext = tracer.extract(FORMAT_TEXT_MAP, msgIn.headers);
    const span = tracer.startSpan('comsumer', {
        references: [
            opentracing.followsFrom(parentSpanContext)
        ],
    });
...


```
I got the exception:
TypeError: Cannot read property 'followsFrom' of undefined

also try:

```

    const span = tracer.startSpan('consumer', {
        followsFrom: parentSpanContext,
        tags: {[Tags.SPAN_KIND]: Tags.SPAN_KIND_MESSAGING_CONSUMER,
            [Tags.MESSAGE_BUS_DESTINATION]: "opentracing"}
    });


```

I got a new traceid, and reference is empty.
{"traceID":"3689d1174b9db4be","spanID":"3689d1174b9db4be","flags":1,"operationName":"consumer","references":[],...

what's the problem?

**Comment by yurishkuro** [comment]
it appears your import is incorrect. Does `require('opentracing');` actually export `opentracing`?  Or does it simply export `followsFrom` function?

**Comment by chenyg0911** [comment]
thanks!
I've require the package opentracing and childOf is OK. 
`const { Tags, FORMAT_TEXT_MAP,opentracing } = require('opentracing');
`

it seems opentracing doesn't have the property followsFrom.
Does any on can't give me a example?

**Comment by yurishkuro** [comment]
How about this?
```javascript
const { Tags, FORMAT_TEXT_MAP, followsFrom } = require('opentracing');
// ...
    const span = tracer.startSpan('cosumer', {
        references: [
            followsFrom(parentSpanContext)
        ],
    });
```

**Comment by chenyg0911** [comment]
yes!
It work for me! thanks you very much!

2018-04-13 10:39 GMT+08:00 Yuri Shkuro <notifications@github.com>:

**Comment by yurishkuro** [comment]
enjoy
