### ISSUE TITLE
The static method initTracer in configuration.js missing support for contextKey

### ISSUE THREAD

**Issue by jeffwebster** [jaegertracing/jaeger-client-node#254]
It looks like support for an alternative to the default TRACER_STATE_HEADER_NAME defined in constant.js has been added to tracer.js and text_map_code.js by allowing a 'contextKey' to be passed as an option. However, the initTracer method in configuration.js does not include support for this when creating a new Tracer object. The current code reads like this:

`
return new Tracer(config.serviceName, reporter, sampler, {
      metrics: options.metrics,
      logger: options.logger,
      tags: options.tags,
    });
`

Fixing this seems like a simple update - something like this:

`
return new Tracer(config.serviceName, reporter, sampler, {
      metrics: options.metrics,
      logger: options.logger,
      tags: options.tags,
      contextKey: options.contextKey
    });
`

Is there a reason that contextKey is not supported in the initTracer method?

**Comment by yurishkuro** [comment]
No reason afaik, just not implemented.
