### ISSUE TITLE
Long-running span did not get flushed to the backend

### ISSUE THREAD

**Issue by aviranco** [jaegertracing/jaeger-client-node#261]
Hi,

I've faced two scenarios:
1. Executed span did not write logs until its .finish()'ed. Is it possible to allow updating span logs even if it not finished yet? If not currently - **is it planned to be supported?**
2. I had a long executing span, I guess about 20 minutes of execution, which was not logged at all.
There is any timeout that after that time the span is being deleted? (or not added at the first place)?
If so - **where can I configure it with longer timeout period of waiting until the .finish() is being called?**

Thanks

**Comment by black-adder** [comment]
1) It seems like you already commented on the ticket where this is being tackled (https://github.com/jaegertracing/jaeger/issues/729)
2) There is no timeout, my guess is that the span with all the logs is bigger than the max UDP packet so it's being dropped at the client. We can send the larger spans via http but the work is not currently underway: https://github.com/jaegertracing/jaeger-client-node/issues/170

**Comment by Deadpool1994** [comment]
Well there is one workaround. **span.finish()** internally uses **tracer._report(span)** to report span when finish. What you can do is report span as soon as you create it by calling **tracer._report(span)**. This will allow span on jaeger-UI and also span logs.
