### ISSUE TITLE
finish span with header information

### ISSUE THREAD

**Issue by willihelm** [jaegertracing/jaeger-client-node#265]
How do I finish a span if I only have the header information? Is there a function that I can call like:

`const ctx = this.jaegerClient.extract(FORMAT_HTTP_HEADERS, headers)`
`const span = this.jaegerClient.getSpanFromContext(ctx)`
`span.finish()`

or something like

`const span = this.jaegerClient.getSpanFromHeader(headers)`
`span.finish()`

**Comment by yurishkuro** [comment]
First, if you're writing code like this.jaegerClient, you're indirectly coupling your code with Jaeger. You don't need to do that: call it "tracer" and assume it implements opentracing.Tracer.

You  should only be finishing spans that you started. After you extracted the context from the headers, create a span using

tracer.startSpan(name, {childOf: ctx})

You may want to study https://github.com/yurishkuro/opentracing-tutorial

**Comment by janniswarnat** [comment]
I was looking for the same thing. Just had a look at the tutorial but still do not understand the best way to trace for my use case. It would be great if you could help me out...

I am using https://www.npmjs.com/package/http-proxy and would like to trace a proxied request. Optimally I would like to start the root span in event proxyReq (before the request is forwarded) and finish it in event proxyRes (after the response arrives in the proxy). So I inject the root span context in the http headers of the request to the upstream service (an express app). The upstream service creates a child span to trace its activities and injects the root span context in the http headers of the response. So in event proxyRes the root span context can be extracted from the response headers but there is no way to finish the root span.

Is there a better design to achieve the desired outcome? How can I trace a request over multiple proxy server events?

**Comment by yurishkuro** [comment]
@janniswarnat spans are meant to be started and stopped in the same process, this is a fundamental design of the OpenTracing. There are several ways to deal with proxies:
  * don't trace them at all, let them just pass through the trace context (this is what we do at Uber, although admittedly it reduces the visibility of the request path
  * let proxies create child spans as usual, in which case your span parents would look like [caller service] -> [proxy] -> [receiver service]
  * let proxies decorate the existing span with logs. This is a bit tricky, we used to do that at Uber where we had a parser for HAProxy logs that would create additional spans using the same span ID as seen in the current header and add log events to those spans for various HAProxy events. The Jaeger backend merges spans with the same ID into one.
