### ISSUE TITLE
Connecting to remote jaeger-agent

### ISSUE THREAD

**Issue by brunomacf** [jaegertracing/jaeger-client-node#267]
Hi guys,

is there a way to connect to a remote jaeger-agent? My scenario is: running a microservice inside docker container which i want to trace using jaeger-client-node and agent is running on the host. I saw that we have `reporter.agentHost` and `sampler.host`, but none is working for me.

```
var assert = require("assert");
var initJaegerTracer = require("jaeger-client").initTracer;

function initTracer(serviceName) {
    var config = {
        serviceName: serviceName,
        sampler: {
            type: "const",
            param: 1
        },
        reporter: {
            logSpans: true,
            agentHost: "192.168.99.100"
        },
    };
    var options = {
        logger: {
            info: function logInfo(msg) {
                console.log("INFO ", msg);
            },
            error: function logError(msg) {
                console.log("ERROR", msg);
            },
        },
    };
    return initJaegerTracer(config, options);
}

const tracer = initTracer('test-service');

const sayHello = helloTo => {
    const span = tracer.startSpan("say-hello-2");
    const helloStr = `Hello, ${helloTo}!`;
    console.log(helloStr);
    span.finish();
};

assert(process.argv.length == 3, "Expecting one argument");
const helloTo = process.argv[2];

sayHello(helloTo);

tracer.close(() => process.exit());
```

Example of code i'm trying to use. Agent is running on `192.168.99.100` (a docker-machine).

**Comment by black-adder** [comment]
Hi there, can you check if the jaeger-agent docker container is exposing port 6832? Also, have you ruled out the agent <-> collectors communication issues? ie how do you know the agent isn't receiving the spans?

**Comment by brunomacf** [comment]
@black-adder thanks for the response...closing this issue because i figured that i was exposing jaeger-agent port as tcp instead of udp and this was the cause i couldn't get it working!
