### ISSUE TITLE
Support ENV variables for configuration

### ISSUE THREAD

**Issue by black-adder** [jaegertracing/jaeger-client-node#282]
## Requirement - what kind of business use case are you trying to solve?

Java and golang clients support tracer initialization from environment variables, would be nice for node to fall into line.

Related to #152

**Comment by claudio-viola** [comment]
Related https://github.com/jaegertracing/jaeger-client-node/issues/293

**Comment by eundoosong** [comment]
@black-adder 
I'd like to work on this issue and think simply we can use `||` operator like this.
```node
static _getSampler(config, options) {
    let type = config.sampler.type || process.env.JAEGER_SAMPLER_TYPE;
    let param = config.sampler.param || process.env.JAEGER_SAMPLER_PARAM;
    let host = config.sampler.host || process.env.JAEGER_SAMPLER_HOST;
    let port = config.sampler.port || process.env.JAEGER_SAMPLER_PORT;
    let refreshIntervalMs = config.sampler.refreshIntervalMs || process.env.JAEGER_SAMPLER_REFRESH_INTERVAL;
```

**Comment by yurishkuro** [comment]
Go for it
