### ISSUE TITLE
prom-client exception from default metric name

### ISSUE THREAD

**Issue by t3h2mas** [jaegertracing/jaeger-client-node#287]
## Requirement - what kind of business use case are you trying to solve?

Use prometheus for metrics via the PrometheusMetricsFactory,
following the example from the readme

## Problem - what in Jaeger blocks you from solving the requirement?

I'm getting an `Invalid metric name` exception from `prom-client` for a default jaeger metric

The metric name `play_jaeger:throttler-update` fails validation against this regex `/^[a-zA-Z_:][a-zA-Z0-9_:]*$/` due to the `-` before 'update'

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Make the default jaeger metric names match the rules found here https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels

(in this case, changing the `-` to `_` would allow it to pass validation)

OR 

provide a way to change the default names

**Comment by yurishkuro** [comment]
Ability to configure metrics names is an overkill imo. The metrics factory for prom needs to simply rewrite the names to be compatible with prom client, eg by replacing dash with underscore.

**Comment by black-adder** [comment]
this was resolved: https://github.com/jaegertracing/jaeger-client-node/pull/279 I'll cut a release with the fix.

**Comment by black-adder** [comment]
Just published 3.12.0 which should have the fix
