### ISSUE TITLE
Research - security concerns related to a Web Client support

### ISSUE THREAD

**Issue by jpkrohling** [jaegertracing/jaeger-client-node#291]
One important aspect of tracing web clients is security. Given that this is a code that runs outside of the realm of the tracing backend, some sort of security is required.

This is a research task, to provide some answers before we even start considering expanding the support for web clients:

- [ ] What is the common practice out there? Are clients just allowed to create spans with random IDs?
- [ ] What are the current standards related to public clients and/or secure communications over insecure channels?
- [ ] Which of those concerns would belong to OpenTracing and which would belong to Jaeger?

**Comment by yurishkuro** [comment]
> code that runs outside of the realm of the tracing backend

That isn't much different from tracing with any hosted tracing backend like Stackdriver or x-ray. I think you mean running code outside of the direct control of the application owner.

**Comment by jpkrohling** [comment]
You are correct: I meant that code running in the browser has a different trust level as code that runs on one's backend.
