### ISSUE TITLE
Implement ScopeManager

### ISSUE THREAD

**Issue by sebnow** [jaegertracing/jaeger-client-node#292]
## Requirement - what kind of business use case are you trying to solve?

Support in-context propagation of the active span, to make span management easier.

## Problem - what in Jaeger blocks you from solving the requirement?

From the RFC:

> For platforms where the call-context is explicitly propagated down the execution chain -such as `Go`-, such context can be used to store the active **Span** at all times.
> 
> For platforms not propagating the call-context, it's inconvenient to pass the active **Span** from function to function manually, so OpenTracing should require, for those platforms, that **Tracer** contains a **Scope Manager** that grants access to the active **Span** through a container, called **Scope** (using some call-context storage, such as thread-local or coroutine-local).

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Implement the [ScopeManager RFC](https://github.com/opentracing/specification/blob/master/rfc/scope_manager.md)

**Comment by yurishkuro** [comment]
afaik the ScopeManager is not yet defined in OpenTracing Javascript, so we can't start it here.
