### ISSUE TITLE
Document FlushIntervalMs configuration variable and .close method usage to flush 'partial' traces

### ISSUE THREAD

**Issue by claudio-viola** [jaegertracing/jaeger-client-node#293]
## Requirement - what kind of business use case are you trying to solve?
Problem: Not all traces were logged 
## Problem - what in Jaeger blocks you from solving the requirement?
Tried to dig into it then found out there is a variable called flushIntervalMs that can be passed to the reporter after digging in the code.
Also found out thanks to support from the gitter chat that there is a close method that is going to send the traces.

Traces are dropped without any log created by the logger explaining that tha if app exits before flushIntervalMs. 
New developers coming into the project have to dig in the code to find out usage.
## Proposal - what do you suggest to solve the problem or improve the existing situation?
- Document flushIntervalMs configuration
- Document tracer.close() method for flushing partial traces  and best practice for flushing on process exit

**Comment by o6uoq** [comment]
+1
