### ISSUE TITLE
Investigate high resolution timers

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-node#31]
e.g. https://github.com/openzipkin/zipkin-js/blob/master/packages/zipkin/src/time.js

**Comment by sul4bh** [comment]
Do you guys take external contributions?

I am available to look into this.

**Comment by yurishkuro** [comment]
@sul4bh absolutely. 

https://github.com/uber/jaeger-client-node/blob/master/CONTRIBUTING.md
