### ISSUE TITLE
Environment variable names do not match other Jaeger clients & docs

### ISSUE THREAD

**Issue by koliyo** [jaegertracing/jaeger-client-node#313]
## Requirement - what kind of business use case are you trying to solve?

Monitoring

## Problem - what in Jaeger blocks you from solving the requirement?

The environment variables in the node client does not match the documentation, or the golang client.

Golang and node documentation says `JAEGER_AGENT_HOST`, but the code use `JAEGER_REPORTER_AGENT_HOST`. Same for a couple of other variables.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Update the implementation to match documentation. Good if it matches the golang client!

**Comment by yurishkuro** [comment]
There is a fix pending #311

**Comment by yepninja** [comment]
List of wrong env variables:
- [ ] `JAEGER_REPORTER_AGENT_PORT` -> `JAEGER_AGENT_PORT`
- [ ] `JAEGER_REPORTER_AGENT_HOST` -> `JAEGER_AGENT_HOST`
- [ ] `JAEGER_REPORTER_ENDPOINT` -> `JAEGER_ENDPOINT`
- [ ] `JAEGER_REPORTER_USER` -> `JAEGER_USER`
- [ ] `JAEGER_REPORTER_PASSWORD` -> `JAEGER_PASSWORD`
- [ ] `JAEGER_SAMPLER_HOST` & `JAEGER_AGENT_PORT` -> `JAEGER_SAMPLER_MANAGER_HOST_PORT`

**Comment by yurishkuro** [comment]
@yepninja can this be closed?

**Comment by yurishkuro** [comment]
But is #321 already addressed by #320 (which is merged)?

**Comment by yepninja** [comment]
#320 now old variables are also supported. #321 is about removing them in a major release.

**Comment by yurishkuro** [comment]
ok so it sounds like this issue should be closed? since the "official" (same as other clients) variables are not supported. Removing the deprecated variables is a much lower priority and is tracked by ticket #321.

**Comment by yepninja** [comment]
Yes, this issue should be closed.
