### ISSUE TITLE
Assumes carrier objects have Object prototypes which breaks with node http/2 headers

### ISSUE THREAD

**Issue by ggoodman** [jaegertracing/jaeger-client-node#317]
## Requirement - what kind of business use case are you trying to solve?

Support using jaeger-client with http/2 headers objects.

## Problem - what in Jaeger blocks you from solving the requirement?

Currently, `jaeger-client` assumes that `carrier` objects will have an `Object` prototype and therefore have the `.hasOwnProperty()` method. This is not the case for `require('http2')` `.headers` properties that have `null` prototypes, see: https://github.com/nodejs/node/blob/4b086141b35d8744a1ddd62362e5bf6d7b36c7cf/lib/internal/http2/core.js#L2008

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Instead of relying on `carrier.hasOwnProperty()`, use a helper function like: 

```js
function hop(receiver, property) {
  return Object.prototype.hasOwnProperty.call(receiver, property);
}
```
## Any open questions to address

*N/A*

**Comment by yurishkuro** [comment]
Sounds reasonable; would you like to add a PR?

I would skip the helper function and use `Object.prototype.hasOwnProperty.call()` directly.

**Comment by ggoodman** [comment]
@yurishkuro I've taken a stab in #318.
