### ISSUE TITLE
When can we expect a new release with initTracer fixes

### ISSUE THREAD

**Issue by StarpTech** [jaegertracing/jaeger-client-node#319]
Hi, it would great to get a new release with some important fixes for the `initTracer` method.

* Accept `contextKey` https://github.com/jaegertracing/jaeger-client-node/issues/254
* Accept `baggagePrefix` https://github.com/jaegertracing/jaeger-client-node/commit/7a9c1008568b310ec069e72f3d31134391d3138f

Thank you.

**Comment by Bessonov** [comment]
@StarpTech AFAIK it's already released.

**Comment by StarpTech** [comment]
@Bessonov thanks for the reminder.
