### ISSUE TITLE
Remove deprecated environment variables

### ISSUE THREAD

**Issue by yepninja** [jaegertracing/jaeger-client-node#321]
## Requirement - what kind of business use case are you trying to solve?
Unify configuration with env variables

## Problem - what in Jaeger blocks you from solving the requirement?
Mismatching environment variable naming (#313)

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Bring the configuration with env variables according to jaeger [doc](https://www.jaegertracing.io/docs/1.8/client-features/) in the next major releas

List of env variables to remove:
- [x] `JAEGER_REPORTER_AGENT_PORT`
- [x] `JAEGER_REPORTER_AGENT_HOST`
- [x] `JAEGER_REPORTER_ENDPOINT`
- [x] `JAEGER_REPORTER_USER`
- [x] `JAEGER_REPORTER_PASSWORD`
- [x] `JAEGER_SAMPLER_HOST`
- [x] `JAEGER_SAMPLER_PORT`
- [x] `JAEGER_DISABLE`

**Comment by drbonzo** [comment]
Should `JAEGER_DISABLE` also be fixed?

jaeger-client-node uses `JAEGER_DISABLE` where all docs use `JAEGER_DISABLED`

- `JAEGER_DISABLE`
    - https://github.com/jaegertracing/jaeger-client-node/search?q=JAEGER_DISABLE&unscoped_q=JAEGER_DISABLE

- `JAEGER_DISABLED`
    - https://github.com/jaegertracing/jaeger-client-node/blob/master/README.md#environment-variables
    - https://www.jaegertracing.io/docs/1.8/client-features/

**Comment by yepninja** [comment]
@drbonzo Yes, sure. I'll fix it too.
