### ISSUE TITLE
Problem with publishing npm package

### ISSUE THREAD

**Issue by yepninja** [jaegertracing/jaeger-client-node#322]
## Requirement - what kind of business use case are you trying to solve?
Publish npm package 

## Problem - what in Jaeger blocks you from solving the requirement?
Missed folder `dist/src` in npm package after the update of `.npmingore` #307

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Fix `.nmpignore` or use [whitelist](https://docs.npmjs.com/files/package.json#files) instead of blacklist

**Comment by tiffon** [comment]
Thanks for filing this!

A whitelist will definitely be more succinct. 

Are you saying the `dist/src` is missing after the `.npmignore`? Or, it's missed in the `.npmignore` and should be added to the `.npmignore`?

The main is:
```
"main": "./dist/src/index.js",
```

So, `dist/src` should be in the package. (Using transpiled `dist` is necessary for node 0.10 compatibility.)

**Comment by yepninja** [comment]
I mean that `dist/src` is missing after the `.npmignore`. You can try:
```
npm pack
npm notice
npm notice 📦  @ozon/jaeger-client@3.14.0
npm notice === Tarball Contents ===
npm notice 3.2kB  package.json
npm notice 98B    .gitmodules
npm notice 4.9kB  CHANGELOG.md
npm notice 4.7kB  CONTRIBUTING.md
npm notice 1.4kB  DCO
npm notice 11.4kB LICENSE
npm notice 15.3kB README.md
npm notice 2.1kB  RELEASE.md
npm notice 1.5kB  crossdock/docker-compose.yml
npm notice 483B   crossdock/Dockerfile
npm notice 1.2kB  crossdock/jaeger-docker-compose.yml
npm notice 1.8kB  crossdock/rules.mk
npm notice 3.2kB  dist/package.json
npm notice === Tarball Details ===
npm notice name:          @ozon/jaeger-client
npm notice version:       3.14.0
npm notice filename:      ozon-jaeger-client-3.14.0.tgz
npm notice package size:  16.6 kB
npm notice unpacked size: 51.2 kB
npm notice shasum:        f7c8181798d44cd95f3d949871bd999247651f29
npm notice integrity:     sha512-ilAGTKTVZEamE[...]LO66lleWT6qhQ==
npm notice total files:   13
npm notice
ozon-jaeger-client-3.14.0.tgz
```
