### ISSUE TITLE
Published version@latest has a stale dist

### ISSUE THREAD

**Issue by Matt-Esch** [jaegertracing/jaeger-client-node#323]
## Requirement - what kind of business use case are you trying to solve?

Update jaeger-client to avoid `.hasOwnProperty` failures with node 10 headers

## Problem - what in Jaeger blocks you from solving the requirement?

This is fixed on master/latest but the published package has a stale ./dist directory

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Fix the contents of dist and publish a patch version

## Any open questions to address

Can the publish step be made more fool-proof to prevent stale or missing dist in future?

**Comment by yurishkuro** [comment]
@Matt-Esch what do you mean by "stale dist"? That it does not match the source as of the same version? Can you show how you check this?

**Comment by Matt-Esch** [comment]
There is `./dist` directory at the root of the package. This directory is compiled to (for ES5 back compat I believe using babel). If you `npm i jaeger-client-node@latest` in a node project, you'll see that the installed contents includes the `./dist` directory in the published package, however, the contents are stale. So it appears that the code has been updated but the distributable package has not been re-generated before publishing, from what I can tell at least.

**Comment by yurishkuro** [comment]
@Matt-Esch are you talking about 3.13.0 release? Can you point to specific differences/files that are stale? Since dist contains compiled code I don't know with what I can compare it. When I `git checkout v3.13.0` and run `make build-node` and then compare `dist/src` with `node_modules/jaeger-client/dist/src` in some project that imports Jaeger client 3.13.0, there are no differences between them.

**Comment by Matt-Esch** [comment]
Perhaps it's just something I have done locally then if you can't reproduce. It could be that I was just confused by the way the code was transpiled. If i figure out what it was I was struggling with I'll reopen this issue.
