### ISSUE TITLE
No compact format

### ISSUE THREAD

**Issue by yepninja** [jaegertracing/jaeger-client-node#324]
## Requirement - what kind of business use case are you trying to solve?
Use the same format of reported data. Go client library uses compact format. Jaeger env variable for agent port is set up for compact format.

## Problem - what in Jaeger blocks you from solving the requirement?
Nodejs client uses binary format. And I cann't switch to compact format.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Support change the format.

**Comment by yurishkuro** [comment]
As I recall, at he time there was no support for compact format in the thrift lib we're using. What is your justification for needing it?

**Comment by fho** [comment]
As I understand the ticket, the point is to align the jaeger nodejs and golang libraries.
If a variable has the same name I assume that the same value is expected.
(I  stumbled about the issue myself some minutes ago.)

But:
`JAEGER_AGENT_PORT` for jaeger-client-node expects port 6832 (binary thrift)
`JAEGER_AGENT_PORT` for jaeger-client-go expects port 6831 (compact thrift)

**Comment by yurishkuro** [comment]
The port discrepancy is a separate issue that can be addressed in by auto-detecting the format https://github.com/jaegertracing/jaeger/issues/1596.

**Comment by yurishkuro** [comment]
Doesn't look like we'll be able to solve this here, closing.
