### ISSUE TITLE
Question - Inherit or access tags from parent span

### ISSUE THREAD

**Issue by StarpTech** [jaegertracing/jaeger-client-node#327]
Hi, is it possible that spans inherit tags from the parents or to access parent tags in context of a child span? Currently, it is possible to archive that behavior with Baggage items but they will be only passed for cross-process communication. I would like to have access to the parent span tags in order to avoid passing all the information down to the calls.

**Comment by black-adder** [comment]
Hi, this is currently not possible with the node client. Although we have been playing around with the idea of creating an in process only baggage for jaeger but we haven't gotten very far with the idea yet.
