### ISSUE TITLE
3.14.0 build on npm is missing essential build artifacts and is therefore broken

### ISSUE THREAD

**Issue by ggoodman** [jaegertracing/jaeger-client-node#338]
## Requirement - what kind of business use case are you trying to solve?

Install the node jaeger client.

## Problem - what in Jaeger blocks you from solving the requirement?

The published `dist` dir is missing the relevant contents see [unpkg](https://unpkg.com/jaeger-client@3.14.0/dist/src/). The `package.json` defines a main file of `"./dist/src/index.js"`; this file doesn't exist in the current published version (`3.14.0`).

**Impact**: `jaeger-client` is broken for all new installs with semver ranges satisfied by `3.14.0`.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

I do not know.

## Any open questions to address

N/A

**Comment by black-adder** [comment]
thanks for reporting, looking into it

**Comment by black-adder** [comment]
that didn't work, interestingly it works when doing a dry run locally

**Comment by black-adder** [comment]
uhhh ok, so I followed the exact same publishing steps for for https://www.npmjs.com/package/jaeger-client/v/3.14.2-beta.0 and https://www.npmjs.com/package/jaeger-client/v/3.14.2 but they produced different results, one has dist/src, the other is missing dist completely.

**Comment by pmcclory** [comment]
+1 also running into this.  also seems to effect 3.14.1 and 3.14.2

**Comment by black-adder** [comment]
@ggoodman @pmcclory can you try 3.14.3?

**Comment by black-adder** [comment]
ok, nvm, we're gonna need to do a 3.14.4, npm and package.json...

**Comment by yurishkuro** [comment]
I verified 3.14.4, it seems to work. We had to remove the code that was importing package.json, will need to figure out to add this functionality back.
