### ISSUE TITLE
Fails when running in AWS Lamda when it cannot determine process_ip, ip.split is not a function

### ISSUE THREAD

**Issue by jeffbski** [jaegertracing/jaeger-client-node#342]
## Requirement - what kind of business use case are you trying to solve?

Use jaeger for distributed tracing

## Problem - what in Jaeger blocks you from solving the requirement?

When running in AWS lambda, process_ip is often undefined on subsequent executions so jaeger client throws an error when trying to do ip.split on undefined. 

```json
{"errorMessage":"ip.split is not a function","errorType":
"TypeError","stackTrace":["Function.ipToInt (/var/task/node_modules/jaeger-client/dist/src/util.js:114:22)",
"new Tracer (/var/task/node_modules/jaeger-client/dist/src/tracer.js:120:55)",
"initTracer (/var/task/node_modules/jaeger-client/dist/src/configuration.js:299:14)",
"createTracer (/var/task/log.js:57:10)",
"new Log (/var/task/log.js:68:29)",
"Function.create (/var/task/log.js:73:15)",
"/var/task/wrapLambda.js:5:21"]}
```

Exception causes everything to fail.

I had even tried setting options.tag.ip to '1.2.3.4' to work around but it didn't help.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

We need some way to configure this so it will work in lambda and environments where it cannot determine the process_ip. Is this only needed for tagging purposes, then check if undefined and skip adding the tag if not defined.

**Comment by jeffbski** [comment]
#340 might have fixed the issue since ip.split is no longer called. 

So I think we simply need 3.14.5 published and we should be good.

**Comment by jeffbski** [comment]
I confirmed that indeed what is in master does resolve the problem since it does not try to do an ip.split on undefined. 

```js
    this._tags[constants.PROCESS_IP] = this._tags[constants.PROCESS_IP] || Utils.myIp();
```

Let's get 3.14.5 published with this change and we will be good.

Thanks.

**Comment by jeffbski** [comment]
Can we get 3.14.5 published to npm to fix this please??

**Comment by Bessonov** [comment]
@jeffbski  As I can see, the version was published.

**Comment by jeffbski** [comment]
Thanks for letting me know @Bessonov
