### ISSUE TITLE
Memory leak in HTTP sender

### ISSUE THREAD

**Issue by baldmaster** [jaegertracing/jaeger-client-node#344]
After some time of using jaeger in production a memory leak detected thanks to [heapdump](https://github.com/bnoordhuis/node-heapdump). And here is why.

According to official [documentation](https://nodejs.org/dist/latest-v10.x/docs/api/http.html#http_class_http_clientrequest)

> If no 'response' handler is added, then the response will be entirely discarded. However, **if a 'response' event handler is added, then the data from the response object must be consumed**, either by calling response.read() whenever there is a 'readable' event, or by adding a 'data' handler, or by calling the .resume() method. Until the data is consumed, the 'end' event will not fire. Also, **until the data is read it will consume memory that can eventually lead to a 'process out of memory' error.** 
> 
[furthermore](https://nodejs.org/dist/latest-v10.x/docs/api/http.html#http_http_request_url_options_callback)

> The optional callback parameter will be added as a one-time listener for the **'response' event**. 
> 

It's pretty easy to reproduce. Start up any server, set HTTP jaeger endpoint and make a batch of requests.

before fix
![11-02-2019-19 09 17_1920x1080](https://user-images.githubusercontent.com/6952333/52580856-e6aec780-2e31-11e9-823e-f1fd193a105f.png)

after fix
![11-02-2019-19 10 07_1920x1080](https://user-images.githubusercontent.com/6952333/52582115-1c08e480-2e35-11e9-8d05-26ba81bfaba2.png)

comparison
![11-02-2019-19 10 40_1920x1080](https://user-images.githubusercontent.com/6952333/52582341-a5b8b200-2e35-11e9-91b1-2216aeb0b87a.png)

**Comment by baldmaster** [comment]
Fixed by #343

**Comment by viktorstaikov** [comment]
Is this fix published?

**Comment by tiffon** [comment]
@viktorstaikov No, we just realized this fix fell through the cracks! We will be publishing an update, soon.
