### ISSUE TITLE
initTracer mutates passed options

### ISSUE THREAD

**Issue by fapspirit** [jaegertracing/jaeger-client-node#345]
## Requirement - what kind of business use case are you trying to solve?
Re-usage of configuration and options

## Problem - what in Jaeger blocks you from solving the requirement?
`initTracer` mutates `options`. Example:

```js
const { initTracer } = require('jaeger-client');

const tracing = {
  config: {
    serviceName: 'my-awesome-service'
  },
  options: {
    tags: {
      version: '1.0.0'
    }
  }
};

const Tracer1 = initTracer(tracing.config, tracing.options);
/*
After first initiation, `tracing.config.tags` contains additional data,
which brakes second initiation.
*/
const Tracer2 = initTracer(tracing.config, tracing.options);
```

Error's stack trace:
```
TypeError: ip.split is not a function
    at Function.ipToInt (/node_modules/jaeger-client/dist/src/util.js:115:22)
    at new Tracer (/node_modules/jaeger-client/dist/src/tracer.js:123:39)
    at Object.initTracer (/node_modules/jaeger-client/dist/src/configuration.js:299:14)
```

This error caused because tags inside Tracer referencing to tags from options:
https://github.com/jaegertracing/jaeger-client-node/blob/eb665cd13061a7d2b6b5ac36d86af4ae6aba5516/src/tracer.js#L66

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Cloning options before using them.

**Comment by yurishkuro** [comment]
PRs are welcome. However, I don't understand how `TypeError: ip.split is not a function` is related to cloning the config dictionary.

**Comment by fapspirit** [comment]
Just to clarify the code state, I'm using `3.14.3` version.

Let me explain what's going on in code snippet from my previous comment:
1. I have the `tracing` object, which contains `config` and `options`. I pass them as arguments to `initTracer`
2. I call `initTracer(tracing.config, tracing.options)` for the 1st time which returns `Tracer`, as expected
3. When I call `initTracer` one more time with same params (same `tracing` object), I get `TypeError: ip.split is not a function` and here is why:
After calling `initTracer` for the first time, `tracer.options.tags` contains additional fields, which was assigned inside `initTracer`. Look at this assignment:
https://github.com/jaegertracing/jaeger-client-node/blob/8db16e081c8604a970263c648b203081021eb229/src/tracer.js#L71
For the 1st call, there is no `ip` in `tags` so `Utils.ipToInt` receives value from `Utils.myIp()` (because `this._tags.ip` is `undefined`) and then assign `Int` representation of ip to `tags.ip`. Since `this._tags` referencing to `tracing.options.tags`, this assignment mutates argument. Then, on 2nd call of `initTracer` with same params, `Utils.ipToInt` receives value from `this._tags.ip` (because it's no longer `undefined`). Since stored value have `typeof Number`, it doesn't have `split` method, that's why there is `TypeError`.

This problem happens only if the same `options` object passed on every call of `initTracer`. And this problem can be solved by avoiding of user's data mutation.

At this moment (in master branch), there is no longer `IpToInt` transformation, I suppose it should fix `TypeError`:
https://github.com/jaegertracing/jaeger-client-node/blob/eb665cd13061a7d2b6b5ac36d86af4ae6aba5516/src/tracer.js#L70
However, mutating user's data is not a good practice, I will try to fix this later this week and create a PR

**Comment by yurishkuro** [comment]
Great, PR would be welcome.

On a separate note, why are you creating the tracer more than once in the same app?

**Comment by fapspirit** [comment]
I creating configurable modular tooling, which may work together (like battery-included server) or like standalone tools. There is some complexity of context management, I need to create spans in different modules, so I decided to create tracers independently but with the same configuration.
