### ISSUE TITLE
Agent usage with http sender.

### ISSUE THREAD

**Issue by yrsh** [jaegertracing/jaeger-client-node#349]
## Requirement - what kind of business use case are you trying to solve?
We use http-sender, i.e. client must sends spans direct to collector, but seems it tries connect agent.

## Problem - what in Jaeger blocks you from solving the requirement?
After reload of Jaeger collector we've got error in logs:
```
Error in fetching sampling strategy: Error: connect ECONNREFUSED 0.0.0.0:5778.
```
5778 is default agent port. Why does jaeger tries connect to agent, if only http-sender has been configured? It should not use agent at all.
## Proposal - what do you suggest to solve the problem or improve the existing situation?
Do not try connect to agent, if only collector is used.

jaeger-client version - 3.14.4

**Comment by yurishkuro** [comment]
It may be still using http on agent for sampling strategies. We never implemented that http endpoint on the collectors  (https://github.com/jaegertracing/jaeger/issues/1420)
