### ISSUE TITLE
Usage of GuaranteedThroughputSampler

### ISSUE THREAD

**Issue by morriq** [jaegertracing/jaeger-client-node#352]
## Requirement - what kind of business use case are you trying to solve?

I'm trying to implement same sampling strategy as we have in c# projects, WHICH have posibility to set [Guaranteed Throughput Probabilistic Sampler](https://github.com/jaegertracing/jaeger-client-csharp/blob/master/src/Jaeger/Samplers/README.md#guaranteed-throughput-probabilistic-sampler)

## Problem - what in Jaeger blocks you from solving the requirement?

How can I implement it in nodejs? I checked sourcodes and it seems that `GuaranteedThroughputSampler` is part of `RemoteSampler`. so no chances to implement it without remote sampler?

**Comment by yurishkuro** [comment]
part of RemoteSampler in what sense? It's a standalone class https://github.com/jaegertracing/jaeger-client-node/blob/master/src/samplers/guaranteed_throughput_sampler.js#L25
