### ISSUE TITLE
How to set IDs in SpanContext

### ISSUE THREAD

**Issue by imrefazekas** [jaegertracing/jaeger-client-node#358]
Hello,

I'm using nats messaging and I would love to see the IDs (messageID, correlationID) within the SpanContext in order to be able to see the flow by these IDs.
As I can tell, that APi does not allow me to set these IDs at all.
Is there a way to force SpanContext to receive ids from outside? It is not too convenient to use new ids since I already have ones and those IDs already defines the graph of the calls implicityly.

Thanks!

**Comment by yurishkuro** [comment]
This is not something we explicitly support (relevant discussion in https://github.com/opentracing/specification/issues/137).
