### ISSUE TITLE
Can SRV records be used for Jaeger Client?

### ISSUE THREAD

**Issue by ndurant-sp** [jaegertracing/jaeger-client-node#359]
## Requirement - what kind of business use case are you trying to solve?

To support using Jaeger in our lambdas in AWS, we've set up agents using Route53 service discovery with SRV records (because we don't use awsvpc networking).  Looking to use SRV DNS records to push the traces to the Agents from the nodejs jaeger client.

## Problem - what in Jaeger blocks you from solving the requirement?

Want to see if this use case is possible to be able to cleanly use Jaeger in our Lambdas while still leveraging UDP.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

If not, only other alternative I see is using HTTP mode with a load balancer. 

## Any open questions to address

Other possible alternatives?

**Comment by yurishkuro** [comment]
I think HTTP to collector is better from lambdas. UDP is not recommended if you cannot guarantee that the agent runs on the same host as the app, because the packets might be lost and/or fragmented.
