### ISSUE TITLE
Supporting followsFrom

### ISSUE THREAD

**Issue by Saeed-Ataee** [jaegertracing/jaeger-client-node#367]
Hi there,

Is this module supports `followsFrom` reference type? I tried `childOf` and this works fine, but whenever I use `followsFrom` it does not work and creates two unrelated spans!

Works fine
`
tracer.startSpan('childSpan', {'childOf': parentSpan});
`

Does not work
`
tracer.startSpan('childSpan', {'followsFrom': parentSpan});
`

**Comment by yurishkuro** [comment]
`followsFrom` cannot be passed via top-level key, the API only allows passing those as Reference objects:

https://github.com/opentracing/opentracing-javascript/blob/21a860903392889780f0397a602e98234057f6e1/src/tracer.ts#L7

**Comment by Saeed-Ataee** [comment]
[this](https://github.com/opentracing/opentracing-javascript/blob/21a860903392889780f0397a602e98234057f6e1/src/tracer.ts#L71) example helps me.
```
let referenceTypes = {
  'childOf': 'childOf',
  'ChildOf': 'childOf',
  'followsFrom': 'followsFrom',
  'FollowsFrom': 'followsFrom'
};
let
  reference = {};

if (referenceTypes[options.referenceType] == 'followsFrom') {
  reference['references'] = [
    opentracing.followsFrom(options.span.context())
  ];
}
else {
  reference[referenceTypes[options.referenceType]] = options.span;
}
self._span = _tracer.startSpan(options.title, reference);
```

An example for `options`  will be:

```
{
  title: 'my-span,
  referenceType: 'followsFrom',
  span: parentSpan.getSpan()
}
```

Thanks.
