### ISSUE TITLE
Document Request for Inject and Extract with Text Map Carrier

### ISSUE THREAD

**Issue by CHOMNANP** [jaegertracing/jaeger-client-node#370]
## Cannot use same trace ID accross different node of microservices

On the document of [https://opentracing.io/docs/overview/tracers/#propagating-a-trace-with-inject-extract](url), there is a concept of inject and extract. This is working fine with http carrier. Yet, I cannot reproduce this with Text Map carrier.

Please create a doc for using inject and extract using Text Map Carrier.

This could be key usage for microservices. If this working fine, I believe that more people will adopting this.

**Comment by yurishkuro** [comment]
Hm, you're correct, https://github.com/opentracing/opentracing-javascript doesn't show an example.

Unfortunately, the narrative for Lesson 3 in my Javascript tutorial is not finished, but the code examples are there: https://github.com/yurishkuro/opentracing-tutorial/tree/master/nodejs/lesson03. If you'd like to see the narrative, pick Lesson 3 in another language, as the principles are the same.

PS if after that you feel like creating a pull request to this repo's README or to Lesson 3 in the tutorial, that would be much appreciated.

**Comment by CHOMNANP** [comment]
Hi @yurishkuro, I have no issue in creating a pull request for the tutorial. I have successfully manage to inject and extract the spanContext within the single running node.

Yet, I cannot reproduce this across 2 different node. Here's the steps and I am trying to achieved.

### Node 1
1. Running a node 
2. Create a trace
3. Create a rootSpan from the trace
4. create a childSpan reference to the root span
5. Inject the rootSpan to the trace with TEXT_MAP {id: 123}

### Node 2
1. Running a different node
2. extract the rootSpan from the trace with TEXT_MAP {id: 123} 
- as a result, the rootSpan context is empty. It look like the traceId and rootSpanId is not shared from Node 1.
3. create a span and referent to rootSpan.
- as a result, I got 2 trace within Jaeger UI. which it supposed to be only 1 trace.

Please refer to the code here.
https://github.com/CHOMNANP/jaeger-js-text-map-demo

**Comment by CHOMNANP** [comment]
As you mentioned, then it should look like this.
https://www.jaegertracing.io/docs/1.13/client-libraries/#trace-span-identity

Let me give a try and see if I can pull out the TraceId and SpanID from root context.

**Comment by CHOMNANP** [comment]
I just got it working. I'll push a new PR to the example for this soon.
What should be the name of this?

**Comment by yurishkuro** [comment]
@CHOMNANP the name of what?
