### ISSUE TITLE
Parent and span IDs are not shared for rpc traces

### ISSUE THREAD

**Issue by jmoney8080** [jaegertracing/jaeger-client-node#400]
## Requirement - what kind of business use case are you trying to solve?

We want to share the same the same span and parent as the parent span for rpc requests.

## Problem - what in Jaeger blocks you from solving the requirement?

Currently, the jaeger node client does not follow the pattern for zipkin-rpc where the parentIds and spanIds are shared between the client and child for span.kind=rpc.

Add an option, that's defaulted to off, that allows the sharing of parent and spans for rpc requests.

**Comment by yurishkuro** [comment]
Could you elaborate why you want to do that?

> Currently, the jaeger node client does not follow the pattern for zipkin-rpc

Yes, by design. In fact, even if you share client/server span IDs, Jaeger backend will de-dupe them again, an unnecessary work if you're using Jaeger clients in the first place.

**Comment by jmoney8080** [comment]
So the node client may not support this by design but the java one does: Java configuration for reference: https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/src/main/java/io/jaegertracing/internal/JaegerTracer.java#L613-L616

we use both node and java stacks and and rpcs across both.  so this has caused us to monkeyPatch the node version to get parity up to the java version.

**Comment by yurishkuro** [comment]
I meant that Jaeger clients by design do not reuse span IDs. The shared IDs supported in Java and Go are more for legacy reasons and compatibility with Zipkin.

If you're using Jaeger clients in both Node and Java, why are you configuring Java for shared span IDs?

Also, even if some nodes in the graph use shared IDs, it does mean all nodes must do that. As I said, Jaeger backend will dedupe the IDs anyway.

**Comment by jmoney8080** [comment]
It's for the zipkin compatibility.  We're still using zipkin v1 in a lot of places and we see the java spans being shared through the java client.  For the node we didn't so we monkey patched the startSpan method in a recent upgrade, where the startSpan method was basically rewritten due to sampling being redone, it caused us a headache for bascially a 5-6 line monkeyPatch.  So we were hoping to make the java and node clients feature parity so we can remover the monkeyPatch.  We're picking up go for some of our proxy layers and have noticed it also supporting this zipkin feature.  so we're just trying to make node feature parity with the rest of the clients to so we can remove our monkey patch.

**Comment by jmoney8080** [comment]
What *may* be missing in my description of the setup is, we're not using the jaeger backend/server or whatever for collecting traces.  We stood up our own "trace connector" that takes the zipkins spans and converts them to the haystack format and we use haystack for distributing tracing.  We are just using the clients from jaeger because we like how easy it is to spin them up and we already had a few in place.  The rpc part is really the only issue and it's only for node.

**Comment by jmoney8080** [comment]
I attached a PR above if that helps in the matter
