### ISSUE TITLE
Info about logging

### ISSUE THREAD

**Issue by ric79** [jaegertracing/jaeger-client-node#404]
Hello,
on my application, I'm able to see span.logs on jaeger ui. 

I would like to send into span.logs also the logs created by winston.js logger 

       logger.info("ME TOO")
       span.log({'event': 'OK'});

Is it possible?

Riccardo

**Comment by yurishkuro** [comment]
It's somewhat complicated in JS. In Java the context propagation usually works with thread-locals, so once you make a call into `logger.info()`, it can still access the current trace context and add the logs the the span. If you're using continuation-local storage for context propagation, then you might be able to use the same approach.

**Comment by ric79** [comment]
OK, thanks
