### ISSUE TITLE
How to get the the span id from a span

### ISSUE THREAD

**Issue by nicohagen** [jaegertracing/jaeger-client-node#406]
Hello,

I noticed that SpanContext exposes `toSpanId()` and `toTraceId()` methods, but those are `undefined` for my span.context(). To work around i currently go for this approach:

```
const span = opentracing.globalTracer().startSpan(request.path)
const spanId = (span.context() as any)._spanIdStr
```

How do you do this right actually? Thanks in advance!

**Comment by yurishkuro** [comment]
We probably never upgraded to the latest OpenTracing JS API. Feel free to open a PR to add those methods to Jaeger's SpanContext
