### ISSUE TITLE
Reduce the use of url encoding

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-node#41]
URL encoding of the tracing headers showed up as a large part of the flame graph. We need to minimize its use
- we do not need to invoke url encoding for encoding trace IDs, because x:y:z:w format is safe for http headers
- when decoding trace IDs, we should first try `split(":")`, and only if that didn't work we can try urlDecode
- for baggage values we should always use url encoding, in each direction

**Comment by frankgreco** [comment]
There are 3 todos referenced in this issue. It appears like some are already done. Here is what I see:

> we do not need to invoke url encoding for encoding trace IDs, because x:y:z:w format is safe for http headers

This seems to already be happening with [these](https://github.com/uber/jaeger-client-node/blob/master/src/propagators/text_map_codec.js#L102) lines of code:

```js
carrier[this._contextKey] = stringSpanContext; // no need to encode this
```

> when decoding trace IDs, we should first try` split(":")`, and only if that didn't work we can try urlDecode

#138

> for baggage values we should always use url encoding, in each direction

For encoding, this seems to be accomplished with [this](https://github.com/uber/jaeger-client-node/blob/master/src/propagators/text_map_codec.js#L104-L110) code:

```js
let baggage = spanContext.baggage;
for (let key in baggage) {
     if (baggage.hasOwnProperty(key)) {
          let value = this._encodeValue(spanContext.baggage[key]);
          carrier[`${this._baggagePrefix}${key}`] = value;
     }
}
```

For decoding, this seems to be accomplished with [this](https://github.com/uber/jaeger-client-node/blob/master/src/propagators/text_map_codec.js#L86-L91) code:

```js
} else if (lowerKey === constants.JAEGER_BAGGAGE_HEADER) {
     this._parseCommaSeparatedBaggage(baggage, this._decodeValue(carrier[key]));
} else if (Utils.startsWith(lowerKey, this._baggagePrefix)) {
     let keyWithoutPrefix = key.substring(this._baggagePrefix.length);
     baggage[keyWithoutPrefix] = this._decodeValue(carrier[key]);
}
```
