### ISSUE TITLE
Proposal: Convert thrift IDL files to standard JavaScript imports during build

### ISSUE THREAD

**Issue by jamietre** [jaegertracing/jaeger-client-node#421]
## Requirement - what kind of business use case are you trying to solve?

I would like to be able to deploy `jaeger-client-node` in a standalone WebPack bundle. At present, it cannot be bundled with WebPack only because it loads thrift types from the filesystem at runtime. So even when bundled, the IDLs must still be present in the file system at runtime.

This can require additional or complex configuration for projects that otherwise can be deployed as a single webpack bundle.  It can also lead to confusing errors when added to an existing webpack build; e.g.

https://gitter.im/jaegertracing/Lobby?at=5e3d30e3e8a83835591efc19
https://github.com/jaegertracing/jaeger-client-node/issues/368#issuecomment-517771665

## Problem - what in Jaeger blocks you from solving the requirement?

`jaeger-client-node` has runtime dependencies on assets in the file system

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Refactor client to include IDLs as static build-time dependencies instead of loading the from the filesystem at runtime. This involves a new build step to convert the IDLs to a standard JavaScript module, and removes a build step to copy the IDLs to `dist`

## Any open questions to address

None that I'm aware of. @yurishkuro indiciated [here](https://github.com/jaegertracing/jaeger-client-node/issues/368#issuecomment-585357211) that this would be reasonable. I'm opening this issue to comply with the contribution guidelines, so the PR can reference a more explicit problem description than the ad-hoc conversation in the aforementioned issue.

I've pretty much got a PR ready so can make that soon, unless there are other issues of concern here.

**Comment by yurishkuro** [comment]
+1

**Comment by JapuDCret** [comment]
+1
