### ISSUE TITLE
Debug-only SpanContext cannot be used with Follows-From

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-node#432]
Reposting from https://github.com/jaegertracing/jaeger-client-node/issues/162#issuecomment-613389602

Our code looks like this:

```typescript
const parentContext = tracer.extract(
  FORMAT_HTTP_HEADERS,
  headers,
)
const spanOptions: opentracing.SpanOptions = {
  startTime: startTime.getTime(),
  tags: {
    // ...
  },
}

// Adding this causes problems
if (parentContext != null) {
  spanOptions.references = [opentracing.followsFrom(parentContext)]
}

// edited comment to add this line
const span = tracer.startSpan(OPERATION_NAME, spanOptions)
```

We get the following error:

`Failed to append spans in reporter: error converting span to Thrift: spanId: missing required field "spanId" with id 4 on SpanRef`

We've needed to change it to the following:

```typescript
if (parentContext != null) {
  if ((parentContext as any)._spanIdStr != null) {
    spanOptions.references = [opentracing.followsFrom(parentContext)]
  }
}
```

Curiously we don't get the same error with `spanOptions.childOf`.

**Comment by yurishkuro** [comment]
@ThomWright out of curiosity, why are you using follows-from if the parent context is extracted from an HTTP request?

**Comment by yurishkuro** [comment]
Also, instead of checking for `_spanIdStr`, you may want to check `parentContext.isValid` instead (which is not OpenTracing method, it's Jaeger implementation, but at least it's public).

**Comment by ThomWright** [comment]
> @ThomWright out of curiosity, why are you using follows-from if the parent context is extracted from an HTTP request?

It isn't extracted from an HTTP request. We are using the HTTP header format though.


> Also, instead of checking for `_spanIdStr`, you may want to check `parentContext.isValid` instead (which is not OpenTracing method, it's Jaeger implementation, but at least it's public).

Cool, I'll try that, thanks.
