### ISSUE TITLE
ref.type is not a function while using follows_from

### ISSUE THREAD

**Issue by Elhen15** [jaegertracing/jaeger-client-node#434]
hey,
im trying to use follows_from to make reference between spans,
this is my code block:
`span = tracer.startSpan('some-operation',{references: [{type: REFERENCE_FOLLOWS_FROM, followsFrom: span}]})`

ofcourse that the follow span is not null, and has been created succefully. 
I got the error of ref.type is not a function, but I can see the type of the reference as variable

https://github.com/jaegertracing/jaeger-client-node/blob/4dd7b3e8d2282241e8be55203331c13eb8208028/src/tracer.js#L223

**Comment by yurishkuro** [comment]
See OpenTracing API documentation: https://github.com/opentracing/opentracing-javascript/blob/9aaa299d92a737dbfeabdabff96a5831ca548f7b/src/tracer.ts#L71

**Comment by Elhen15** [comment]
Thanks,
Can I extend the readme file of jaeger-client?
I think this should be in the documentation of jaeger-client too

**Comment by yurishkuro** [comment]
sure, feel free to put a PR
