### ISSUE TITLE
Inconsistency with jaeger-agent probabilistic sampling rate number range

### ISSUE THREAD

**Issue by tiagonapoli** [jaegertracing/jaeger-client-node#435]
## Requirement - what kind of business use case are you trying to solve?

I'm trying to use remote sampling on my node application.

## Problem - what in Jaeger blocks you from solving the requirement?

The data the client receives from the jaeger-agent is the following:
```
{
  strategyType: 'PROBABILISTIC',
  probabilisticSampling: { samplingRate: 5 }
}
```
I expected this to be probabilistic:5%, but when this data is commited to the local probabilistic sampler the value is not divided by 100, then the samplingRate becomes 5 instead of 0.05:
https://github.com/jaegertracing/jaeger-client-node/blob/4e52fa9ef8f74bda6327a71143896b1021d5b2bd/src/samplers/remote_sampler.js#L164-L171

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Maybe the jaeger-client-node should divide the incoming probabilistic sampling rate? I don't know what is the expected number range on the jaeger-agent sampling response (is it 0 -> 100?).

**Comment by yurishkuro** [comment]
Did you configure `samplingRate: 5` yourself in the collector? It's not something that Jaeger would send by default.

The rate is 0..1

**Comment by tiagonapoli** [comment]
Yes, the backend is deployed using jaeger-operator, with the config on sampling:
```
  sampling:
    options:
      default_strategy:
        type: probabilistic
        param: 5
```

**Comment by yurishkuro** [comment]
5 is invalid value, it should be 0.05 for 5%

**Comment by tiagonapoli** [comment]
Maybe I could open an issue and the a PR to update this then?
https://github.com/jaegertracing/documentation/blob/876ddf46d2643ea65d02554f6c5aa0cedf16816f/content/docs/next-release/operator.md#defining-sampling-strategies

**Comment by yurishkuro** [comment]
Please do!

**Comment by tiagonapoli** [comment]
Thanks! Will close this issue
