### ISSUE TITLE
Link to tutorial repository opentracing-tutorial

### ISSUE THREAD

**Issue by a1300** [jaegertracing/jaeger-client-node#449]
## Requirement - what kind of business use case are you trying to solve?

Thank you very much for this great library! It took me some time to get `inject` and `extract` working on different nodes. I didn't knew of the repository [opentracting-tutorial](https://github.com/yurishkuro/opentracing-tutorial). Would it be ok to add a link to the `opentracting-tutorial` repository? I think it will help for many to get started. If ok, I will create  a PR

## Problem - what in Jaeger blocks you from solving the requirement?

No problem

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Already described in Requirement section

**Comment by yurishkuro** [comment]
Yes it's fine to link to it, we already do that from the main website

**Comment by a1300** [comment]
@yurishkuro ok, thanks.
