### ISSUE TITLE
Migrate CI to GitHub Actions

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-node#452]
Similar to https://github.com/jaegertracing/jaeger/issues/2645

* [x] migrate steps from .travis.yml to GHA workflows
* [x] update build badges in README
* [x] remove .travis.yml
* [x] change required checks to new GH jobs

**Comment by tylerauerbeck** [comment]
@yurishkuro Happy to take a look at this if you're still looking for help

**Comment by yurishkuro** [comment]
Much appreciated

**Comment by yurishkuro** [comment]
Thanks, @tylerauerbeck ! All looks good now, closing.
