### ISSUE TITLE
Jaeger client node can't report span with https protocol via AWS API Gateway.

### ISSUE THREAD

**Issue by strada501** [jaegertracing/jaeger-client-node#456]
## Requirement - what kind of business use case are you trying to solve?

I want to collect tracing data with the following architecture.
Jaeger client library nodejs(AWS Lambda) --(HTTPS)--> REST API Proxy(AWS API Gateway) --(HTTP)--> Istio Ingress Gateway(AWS Network Load Balancer) --(HTTP)--> Jaeger Collector Service (k8s)

## Problem - what in Jaeger blocks you from solving the requirement?

When I execute Span report from Jaeger Client Library(NodeJS) via AWS API Gateway using HTTPS protocol, almost 400 error is returned from jaeger collector. HTTP 202 is answered about once every 30 times, but even in that case, the registered Span cannot be confirmed with Jaeger's UI. However, the service name and operation name are displayed in the pull-down menu, so it seems that they are registered.

If this problem cannot be resolved we will not be able to collect tracing data using secure protocols.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

I don't know how to solve this problem so please support me.

## Any open questions to address

By the way, does the Jaeger Client Library support the HTTPS protocol?

**Comment by alexandruluca** [comment]
My reply is a bit late but you could try following.

The request which is sent has an application/x-thrift header. I'm not 100% without testing myself but you could try to enable "passthrough" in your api gateway for that specific header.
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings-configure-with-console.html
