### ISSUE TITLE
ConfigurationEnv doesn't allow falsy values

### ISSUE THREAD

**Issue by Gerrit-K** [jaegertracing/jaeger-client-node#460]
We wanted to disable the tracer based on environment variables and some docs suggested to use `config.sampler = {type: 'const', param: 0}` instead of `config.disable = true`. Trying this we found that the parsing method `ConfigurationEnv._getConfigValue` doesn't handle falsy values (like `param: 0` above) very well:

https://github.com/jaegertracing/jaeger-client-node/blob/4c739a26d57c615fb4ac53eae921b9fd5ca53df2/src/configuration_env.js#L40-L42

The function will fall back to the default value, which in most cases is `process.env.*`, which in turn will be `undefined` if you don't provide it explicitly. `undefined` however is not an allowed value for many options (including `sampler.param`) which will result in errors. 

It would probably make more sense to explicitly check for `null` and / or `undefined` instead of doing an implicit boolean evaluation of the value.

**Comment by yurishkuro** [comment]
would you like to submit a PR?
